security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            http_basic:
                realm: "Area Segura"

    access_control:
#        - { path: ^/guia, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        in_memory:
            memory:
                users:
                    nax:  { password: nax, roles: 'ROLE_USER' }
#        administrators:
#            entity: { class: EtsiAppGuiasBundle:Profesor, property: username }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
#        Etsi\AppGuiasBundle\Entity\Profesor:
#            algorithm:        sha1
#            encode_as_base64: false
#            iterations:       1