eaga_asignatura_index:
    pattern:  /
    defaults: { _controller: EtsiAppGuiasBundle:AdminAsignatura:index }

eaga_asignatura_new:
    pattern:  /new
    defaults: { _controller: EtsiAppGuiasBundle:AdminAsignatura:new }

eaga_asignatura_edit:
    pattern:  /edit/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminAsignatura:edit }

eaga_asignatura_delete:
    pattern:  /delete/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminAsignatura:delete }
