eaga_competencia_index:
    pattern:  /
    defaults: { _controller: EtsiAppGuiasBundle:AdminCompetencia:index }

eaga_competencia_new:
    pattern:  /new
    defaults: { _controller: EtsiAppGuiasBundle:AdminCompetencia:new }

eaga_competencia_edit:
    pattern:  /edit/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminCompetencia:edit }

eaga_competencia_delete:
    pattern:  /delete/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminCompetencia:delete }
