eaga_profesor_index:
    pattern:  /
    defaults: { _controller: EtsiAppGuiasBundle:AdminProfesor:index }

eaga_profesor_new:
    pattern:  /new
    defaults: { _controller: EtsiAppGuiasBundle:AdminProfesor:new }

eaga_profesor_edit:
    pattern:  /edit/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminProfesor:edit }

eaga_profesor_delete:
    pattern:  /delete/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminProfesor:delete }
