admin_role:
    pattern:  /
    defaults: { _controller: "EtsiAppGuiasBundle:Role:index" }

admin_role_show:
    pattern:  /{id}/show
    defaults: { _controller: "EtsiAppGuiasBundle:Role:show" }

admin_role_new:
    pattern:  /new
    defaults: { _controller: "EtsiAppGuiasBundle:Role:new" }

admin_role_create:
    pattern:  /create
    defaults: { _controller: "EtsiAppGuiasBundle:Role:create" }
    requirements: { _method: post }

admin_role_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EtsiAppGuiasBundle:Role:edit" }

admin_role_update:
    pattern:  /{id}/update
    defaults: { _controller: "EtsiAppGuiasBundle:Role:update" }
    requirements: { _method: post }

admin_role_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EtsiAppGuiasBundle:Role:delete" }
    requirements: { _method: post }
