eaga_grado_index:
    pattern:  /
    defaults: { _controller: EtsiAppGuiasBundle:AdminGrado:index }

eaga_grado_new:
    pattern:  /new
    defaults: { _controller: EtsiAppGuiasBundle:AdminGrado:new }

eaga_grado_edit:
    pattern:  /edit/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminGrado:edit }

eaga_grado_delete:
    pattern:  /delete/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminGrado:delete }