eaga_semana_index:
    pattern:  /
    defaults: { _controller: EtsiAppGuiasBundle:AdminSemana:index }

eaga_semana_new:
    pattern:  /new
    defaults: { _controller: EtsiAppGuiasBundle:AdminSemana:new }

eaga_semana_edit:
    pattern:  /edit/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminSemana:edit }

eaga_semana_delete:
    pattern:  /delete/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminSemana:delete }
