eaga_guia_index:
    pattern:  /
    defaults: { _controller: EtsiAppGuiasBundle:AdminGuia:index }

eaga_guia_delete:
    pattern:  /delete/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminGuia:delete }
