eaga_area_index:
    pattern:  /
    defaults: { _controller: EtsiAppGuiasBundle:AdminArea:index }

eaga_area_new:
    pattern:  /new
    defaults: { _controller: EtsiAppGuiasBundle:AdminArea:new }

eaga_area_edit:
    pattern:  /edit/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminArea:edit }

eaga_area_delete:
    pattern:  /delete/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminArea:delete }
