etsi_site_homepage:
    pattern:  /home
    defaults: { _controller: EtsiSiteBundle:Default:home }

etsi_site_contenido:
    pattern:  /contenido/{slug}
    defaults: { _controller: EtsiSiteBundle:Default:contenido }