eaga_grado_index:
    pattern:  /guias/admin/grados
    defaults: { _controller: EtsiAppGuiasBundle:AdminGrado:index }

eaga_grado_new:
    pattern:  /guias/admin/grado/new
    defaults: { _controller: EtsiAppGuiasBundle:AdminGrado:new }

eaga_grado_edit:
    pattern:  /guias/admin/grado/edit/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminGrado:edit }

eaga_grado_delete:
    pattern:  /guias/admin/grado/delete/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminGrado:delete }