eaga_asignatura_index:
    pattern:  /guias/admin/asignaturas
    defaults: { _controller: EtsiAppGuiasBundle:AdminAsignatura:index }

eaga_asignatura_new:
    pattern:  /guias/admin/asignatura/new
    defaults: { _controller: EtsiAppGuiasBundle:AdminAsignatura:new }

eaga_asignatura_edit:
    pattern:  /guias/admin/asignatura/edit/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminAsignatura:edit }

eaga_asignatura_delete:
    pattern:  /guias/admin/asignatura/delete/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminAsignatura:delete }
