eaga_semana_list:
    pattern:  /guias/admin/semana/list
    defaults: { _controller: EtsiAppGuiasBundle:AdminSemana:list }

eaga_semana_new:
    pattern:  /guias/admin/semana/new
    defaults: { _controller: EtsiAppGuiasBundle:AdminSemana:new }

eaga_semana_edit:
    pattern:  /guias/admin/semana/edit/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminSemana:edit }

eaga_semana_show:
    pattern:  /guias/admin/semana/show/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminSemana:show }