eaga_guia_list:
    pattern:  /guias/admin/guia/list
    defaults: { _controller: EtsiAppGuiasBundle:AdminGuia:list }

eaga_guia_new:
    pattern:  /guias/admin/guia/new
    defaults: { _controller: EtsiAppGuiasBundle:AdminGuia:new }

eaga_guia_edit:
    pattern:  /guias/admin/guia/edit/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminGuia:edit }

eaga_guia_show:
    pattern:  /guias/admin/guia/show/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminGuia:show }