eaga_asignatura_list:
    pattern:  /guias/admin/asignatura/list
    defaults: { _controller: EtsiAppGuiasBundle:AdminAsignatura:list }

eaga_asignatura_new:
    pattern:  /guias/admin/asignatura/new
    defaults: { _controller: EtsiAppGuiasBundle:AdminAsignatura:new }

eaga_asignatura_edit:
    pattern:  /guias/admin/asignatura/edit/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminAsignatura:edit }

eaga_asignatura_show:
    pattern:  /guias/admin/asignatura/show/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminAsignatura:show }
