eaga_profesor_list:
    pattern:  /admin/profesor/list
    defaults: { _controller: EtsiAppGuiasBundle:AdminProfesor:list }

eaga_profesor_new:
    pattern:  /admin/profesor/new
    defaults: { _controller: EtsiAppGuiasBundle:AdminProfesor:new }

eaga_profesor_edit:
    pattern:  /admin/profesor/edit/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminProfesor:edit }

eaga_profesor_show:
    pattern:  /admin/profesor/show/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminProfesor:show }