eaga_competencia_index:
    pattern:  /guias/admin/competencias
    defaults: { _controller: EtsiAppGuiasBundle:AdminCompetencia:index }

eaga_competencia_new:
    pattern:  /guias/admin/competencia/new
    defaults: { _controller: EtsiAppGuiasBundle:AdminCompetencia:new }

eaga_competencia_edit:
    pattern:  /guias/admin/competencia/edit/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminCompetencia:edit }

eaga_competencia_delete:
    pattern:  /guias/admin/competencia/delete/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminCompetencia:delete }
