eaga_semana_index:
    pattern:  /guias/admin/semanas
    defaults: { _controller: EtsiAppGuiasBundle:AdminSemana:index }

eaga_semana_new:
    pattern:  /guias/admin/semana/new
    defaults: { _controller: EtsiAppGuiasBundle:AdminSemana:new }

eaga_semana_edit:
    pattern:  /guias/admin/semana/edit/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminSemana:edit }

eaga_semana_delete:
    pattern:  /guias/admin/semana/delete/{id}
    defaults: { _controller: EtsiAppGuiasBundle:AdminSemana:delete }
