eaga_get_asignatura:
    pattern:  /asignatura/{id}
    defaults: { _controller: EtsiAppGuiasBundle:Get:getAsignatura }

eaga_get_semanas:
    pattern:  /semanas/{id}
    defaults: { _controller: EtsiAppGuiasBundle:Get:getSemanas }

eaga_get_competencia:
    pattern:  /competencia/{id}
    defaults: { _controller: EtsiAppGuiasBundle:Get:getCompetencia }

eaga_get_profesor:
    pattern:  /profesor/{id}
    defaults: { _controller: EtsiAppGuiasBundle:Get:getProfesor }


eaga_search_asignatura:
    pattern:  /asignatura/search/{q}
    defaults: { _controller: "EtsiAppGuiasBundle:Get:searchAsignatura" }

eaga_search_competencia:
    pattern:  /competencia/search/{q}
    defaults: { _controller: "EtsiAppGuiasBundle:Get:searchCompetencia" }

eaga_search_profesor:
    pattern:  /profesor/search/{q}
    defaults: { _controller: "EtsiAppGuiasBundle:Get:searchProfesor" }