login:
    pattern: /login
    defaults: { _controller: EtsiAppGuiasBundle:Security:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout


etsi_app_guia_guia:
    pattern:  /
    defaults: { _controller: EtsiAppGuiasBundle:Guia:index }

etsi_app_guia_guia_pasos:
    pattern:  /guia/{id}
    defaults: { _controller: EtsiAppGuiasBundle:Guia:pasos }

etsi_app_guias_guia_update:
    pattern:  /guia/{id}/update
    defaults: { _controller: EtsiAppGuiasBundle:Guia:update }
    requirements: { _method: post }

etsi_app_guia_guia_new:
    pattern:  /new
    defaults: { _controller: EtsiAppGuiasBundle:Guia:new }
    requirements: { _method: post }

etsi_app_guia_guia_coordinador:
    pattern:  /coordinador
    defaults: { _controller: EtsiAppGuiasBundle:Guia:coordinador }
    requirements: { _method: post }


#EtsiAppGuiasBundle_admin_role:
#    resource: "@EtsiAppGuiasBundle/Resources/config/routing/admin_role.yml"
#    prefix:   /admin/role

etsi_app_guias_admin_area:
    resource: "@EtsiAppGuiasBundle/Resources/config/routing/admin_area_routing.yml"
    prefix:   /admin/area

etsi_app_guias_admin_asignatura:
    resource: "@EtsiAppGuiasBundle/Resources/config/routing/admin_asignatura_routing.yml"
    prefix:   /admin/asignatura

etsi_app_guias_admin_competencia:
    resource: "@EtsiAppGuiasBundle/Resources/config/routing/admin_competencia_routing.yml"
    prefix:   /admin/competencia

etsi_app_guias_admin_grado:
    resource: "@EtsiAppGuiasBundle/Resources/config/routing/admin_grado_routing.yml"
    prefix:   /admin/grado

etsi_app_guias_admin_guia:
    resource: "@EtsiAppGuiasBundle/Resources/config/routing/admin_guia_routing.yml"
    prefix:   /admin/guia

etsi_app_guias_admin_profesor:
    resource: "@EtsiAppGuiasBundle/Resources/config/routing/admin_profesor_routing.yml"
    prefix:   /admin/profesor

etsi_app_guias_admin_semana:
    resource: "@EtsiAppGuiasBundle/Resources/config/routing/admin_semana_routing.yml"
    prefix:   /admin/semana