parameters:
#    etsi_app_guias.example.class: Etsi\AppGuiasBundle\Example

services:
#    etsi_app_guias.example:
#        class: %etsi_app_guias.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
